# Generated by Django 3.2.6 on 2021-11-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ninkname',
            new_name='nickname',
        ),
    ]
